routes/web.php
<?php
Route::get('/', function () { return redirect('/admin/home'); });

// Authentication Routes...
$this->get('login', 'Auth\LoginController@showLoginForm')->name('auth.login');
$this->post('login', 'Auth\LoginController@login')->name('auth.login');
$this->post('logout', 'Auth\LoginController@logout')->name('auth.logout');

// Change Password Routes...
$this->get('change_password', 'Auth\ChangePasswordController@showChangePasswordForm')->name('auth.change_password');
$this->patch('change_password', 'Auth\ChangePasswordController@changePassword')->name('auth.change_password');

// Password Reset Routes...
$this->get('password/reset', 'Auth\ForgotPasswordController@showLinkRequestForm')->name('auth.password.reset');
$this->post('password/email', 'Auth\ForgotPasswordController@sendResetLinkEmail')->name('auth.password.reset');
$this->get('password/reset/{token}', 'Auth\ResetPasswordController@showResetForm')->name('password.reset');
$this->post('password/reset', 'Auth\ResetPasswordController@reset')->name('auth.password.reset');

Route::group(['middleware' => ['auth'], 'prefix' => 'admin', 'as' => 'admin.'], function () {
    Route::get('/home', 'HomeController@index');
    Route::resource('permissions', 'Admin\PermissionsController');
    Route::post('permissions_mass_destroy', ['uses' => 'Admin\PermissionsController@massDestroy', 'as' => 'permissions.mass_destroy']);
    Route::resource('roles', 'Admin\RolesController');
    Route::post('roles_mass_destroy', ['uses' => 'Admin\RolesController@massDestroy', 'as' => 'roles.mass_destroy']);
    Route::resource('users', 'Admin\UsersController');
    Route::post('users_mass_destroy', ['uses' => 'Admin\UsersController@massDestroy', 'as' => 'users.mass_destroy']);
    Route::resource('categories', 'CategoryController');
    Route::post('category._mass_destroy', ['uses' => 'CategoryController@massDestroy', 'as' => 'categories.mass_destroy']);
    Route::resource('brands', 'BrandController');
    Route::post('brand._mass_destroy', ['uses' => 'BrandController@massDestroy', 'as' => 'brands.mass_destroy']); 
    Route::resource('jobs', 'JobController');
    Route::post('job._mass_destroy', ['uses' => 'JobController@massDestroy', 'as' => 'jobs.mass_destroy']);  
    Route::resource('employees', 'EmployeeController');
    Route::post('employee._mass_destroy', ['uses' => 'EmployeeController@massDestroy', 'as' => 'employees.mass_destroy']);
    Route::resource('products', 'ProductController');
    Route::post('product._mass_destroy', ['uses' => 'ProductController@massDestroy', 'as' => 'products.mass_destroy']);
    Route::resource('takeorders', 'TakeOrderController');
    Route::get('take', ['uses' => 'TakeOrderController@take', 'as' => 'takeorders.take']);
    Route::put('take/{id}', ['uses' => 'TakeOrderController@takeUpdate', 'as' => 'takeorders.takeedit']);

    Route::resource('orders', 'OrderController');
    Route::post('order._mass_destroy', ['uses' => 'OrderController@massDestroy', 'as' => 'orders.mass_destroy']);    
    Route::resource('orderitems', 'OrderItemController');
    Route::post('orderitem._mass_destroy', ['uses' => 'OrderItemController@massDestroy', 'as' => 'orderitems.mass_destroy']);
    Route::resource('tables', 'TableController');
    Route::post('table._mass_destroy', ['uses' => 'TableController@massDestroy', 'as' => 'tables.mass_destroy']);

    Route::get('pdf/{id}', ['uses' => 'PdfController@invoice', 'as' => 'pdf.order']);

    Route::get('report/date', ['uses' => 'OrderController@report', 'as' => 'orders.report']);
    Route::get('report/date/generate', ['uses' => 'OrderController@generate', 'as' => 'orders.generate']);

              

});

app/OrderItem.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class OrderItem extends Model
{
   
	protected $table = 'order_items';

	protected $fillable =  ['product_id', 'order_id', 'price', 'observation'];



    public function product()
    {
    	return $this->belongsTo('App\Product');
    } 

    public function order()
    {
    	return $this->hasOne('App\Order');
    } 
}

app/Http/Controllers/OrderItemController.php
<?php

namespace App\Http\Controllers;

use App\OrderItem;
use App\Order;
use App\Product;
use Illuminate\Http\Request;

class OrderItemController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
  
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\OrderItem  $orderItem
     * @return \Illuminate\Http\Response
     */
    public function show($order)
    {
        $orderItems = OrderItem::where('order_id', $order)->get();
        return view('admin.orderitems.index', compact('orderItems'));  
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\OrderItem  $orderItem
     * @return \Illuminate\Http\Response
     */
    public function edit($item)
    {
        $orderItem = OrderItem::where('id', $item)->first();
        $products = Product::pluck('name', 'id');
        return view('admin.orderitems.edit', compact('orderItem', 'products'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\OrderItem  $orderItem
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
          $orderItem = OrderItem::where('id', $id)->first();
          
          $fillable = $request->all();

          $orderItem->fill($fillable)->save();

          return redirect('/admin/orderitems/'.$orderItem->order_id); 
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\OrderItem  $orderItem
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
          $orderItem = OrderItem::where('id', $id)->first();
        
          $order_id = $orderItem->order_id;

          $orderItem->delete();

          return redirect('/admin/orderitems/'.$order_id);
    }

    public function massDestroy(Request $request)
    {
        if (! Gate::allows('users_manage')) {
            return abort(401);
        }
        if ($request->input('ids')) {
            $entries = OrderItem::whereIn('id', $request->input('ids'))->get();

            foreach ($entries as $entry) {
                $entry->delete();
            }
        }
    }         
}

resources/views/admin/orderitems/create.blade.php
@extends('layouts.app')

@section('content')
    <h3 class="page-title">@lang('global.orderitems.title')</h3>
    {!! Form::model($orderItem, ['method' => 'PUT', 'route' => ['admin.orderitems.update', $orderItem->id]]) !!}

    {{ Form::hidden('order_id', $orderItem->order_id) }}
    <div class="panel panel-default">
        <div class="panel-heading">
            @lang('global.app_create')
        </div>
        
        <div class="panel-body">
            <div class="row">
                <div class="col-xs-12 form-group">
                    {!! Form::label('product_id', 'Product', ['class' => 'control-label']) !!}
                    {!! Form::select('product_id', $products, $orderItem->product_id, ["class" => "form-control"])!!}
                </div>
            </div>  
            <div class="row">
                <div class="col-xs-12 form-group">
                    {!! Form::label('observation', 'Observation', ['class' => 'control-label']) !!}
                    {!! Form::text('observation', old('observation'), ['class' => 'form-control', 'placeholder' => '']) !!}
                    <p class="help-block"></p>
                    @if($errors->has('observation'))
                        <p class="help-block">
                            {{ $errors->first('observation') }}
                        </p>
                    @endif
                </div>
            </div>
            <div class="row">
                <div class="col-xs-12 form-group">
                    {!! Form::label('price', 'Price', ['class' => 'control-label']) !!}
                    {!! Form::text('price', $orderItem->price, ['class' => 'form-control', 'placeholder' => '']) !!}
                    <p class="help-block"></p>
                    @if($errors->has('price'))
                        <p class="help-block">
                            {{ $errors->first('price') }}
                        </p>
                    @endif
                </div>
            </div>






        </div>
    </div>
    {!! Form::submit(trans('global.app_update'), ['class' => 'btn btn-danger']) !!}
     <a href="{{ route('admin.orderitems.show',[$orderItem->order_id]) }}" class="btn btn-info">@lang('global.app_back')</a>                                    

    {!! Form::close() !!}

@stop

resources/views/admin/orderitems/edit.blade.php
@extends('layouts.app')

@section('content')
    <h3 class="page-title">@lang('global.orderitems.title')</h3>
    {!! Form::model($orderItem, ['method' => 'PUT', 'route' => ['admin.orderitems.update', $orderItem->id]]) !!}

    {{ Form::hidden('order_id', $orderItem->order_id) }}
    <div class="panel panel-default">
        <div class="panel-heading">
            @lang('global.app_create')
        </div>
        
        <div class="panel-body">
            <div class="row">
                <div class="col-xs-12 form-group">
                    {!! Form::label('product_id', 'Product', ['class' => 'control-label']) !!}
                    {!! Form::select('product_id', $products, $orderItem->product_id, ["class" => "form-control"])!!}
                </div>
            </div>  
            <div class="row">
                <div class="col-xs-12 form-group">
                    {!! Form::label('observation', 'Observation', ['class' => 'control-label']) !!}
                    {!! Form::text('observation', old('observation'), ['class' => 'form-control', 'placeholder' => '']) !!}
                    <p class="help-block"></p>
                    @if($errors->has('observation'))
                        <p class="help-block">
                            {{ $errors->first('observation') }}
                        </p>
                    @endif
                </div>
            </div>
            <div class="row">
                <div class="col-xs-12 form-group">
                    {!! Form::label('price', 'Price', ['class' => 'control-label']) !!}
                    {!! Form::text('price', $orderItem->price, ['class' => 'form-control', 'placeholder' => '']) !!}
                    <p class="help-block"></p>
                    @if($errors->has('price'))
                        <p class="help-block">
                            {{ $errors->first('price') }}
                        </p>
                    @endif
                </div>
            </div>






        </div>
    </div>
    {!! Form::submit(trans('global.app_update'), ['class' => 'btn btn-danger']) !!}
     <a href="{{ route('admin.orderitems.show',[$orderItem->order_id]) }}" class="btn btn-info">@lang('global.app_back')</a>                                    

    {!! Form::close() !!}

@stop

resources/views/admin/orderitems/index.blade.php
@inject('request', 'Illuminate\Http\Request')
@extends('layouts.app')

@section('content')
    <h3 class="page-title">@lang('global.orderitems.title')</h3>

    <p>
        <a href="{{ route('admin.orders.index') }}" class="btn btn-success">@lang('global.app_back')</a>
    </p>
    <div class="panel panel-default">
        <div class="panel-heading">
            @lang('global.app_list')
        </div>

        <div class="panel-body table-responsive">
            <table class="table table-bordered table-striped {{ count($orderItems) > 0 ? 'datatable' : '' }} dt-select">
                <thead>
                    <tr>
                        <th style="text-align:center;"><input type="checkbox" id="select-all" /></th>

                        <th>@lang('global.orderitems.fields.product')</th>
                        <th>@lang('global.orderitems.fields.observation')</th>
                        <th>@lang('global.orderitems.fields.price')</th>
                        <th>&nbsp;</th>

                    </tr>
                </thead>
                
                <tbody>
                    @if (count($orderItems) > 0)
                        @foreach ($orderItems as $item)
                            <tr data-entry-id="{{ $item->id }}">
                                <td></td>

                                <td>{{ $item->product->name }}</td>
                                <td>{{ $item->observation }}</td>
                                <td>{{ $item->price }}</td>
                                <td>
                                    <a href="{{ route('admin.orderitems.edit',[$item->id]) }}" class="btn btn-xs btn-info">@lang('global.app_edit')</a>
                                    {!! Form::open(array(
                                        'style' => 'display: inline-block;',
                                        'method' => 'DELETE',
                                        'onsubmit' => "return confirm('".trans("global.app_are_you_sure")."');",
                                        'route' => ['admin.orderitems.destroy', $item->id])) !!}
                                    {!! Form::submit(trans('global.app_delete'), array('class' => 'btn btn-xs btn-danger')) !!}
                                    {!! Form::close() !!}
                                </td>

                            </tr>
                        @endforeach
                    @else
                        <tr>
                            <td colspan="9">@lang('global.app_no_entries_in_table')</td>
                        </tr>
                    @endif
                </tbody>
            </table>
        </div>
    </div>
@stop

@section('javascript') 



@endsection