routes/web.php
<?php
Route::get('/', function () { return redirect('/admin/home'); });

// Authentication Routes...
$this->get('login', 'Auth\LoginController@showLoginForm')->name('auth.login');
$this->post('login', 'Auth\LoginController@login')->name('auth.login');
$this->post('logout', 'Auth\LoginController@logout')->name('auth.logout');

// Change Password Routes...
$this->get('change_password', 'Auth\ChangePasswordController@showChangePasswordForm')->name('auth.change_password');
$this->patch('change_password', 'Auth\ChangePasswordController@changePassword')->name('auth.change_password');

// Password Reset Routes...
$this->get('password/reset', 'Auth\ForgotPasswordController@showLinkRequestForm')->name('auth.password.reset');
$this->post('password/email', 'Auth\ForgotPasswordController@sendResetLinkEmail')->name('auth.password.reset');
$this->get('password/reset/{token}', 'Auth\ResetPasswordController@showResetForm')->name('password.reset');
$this->post('password/reset', 'Auth\ResetPasswordController@reset')->name('auth.password.reset');

Route::group(['middleware' => ['auth'], 'prefix' => 'admin', 'as' => 'admin.'], function () {
    Route::get('/home', 'HomeController@index');
    Route::resource('permissions', 'Admin\PermissionsController');
    Route::post('permissions_mass_destroy', ['uses' => 'Admin\PermissionsController@massDestroy', 'as' => 'permissions.mass_destroy']);
    Route::resource('roles', 'Admin\RolesController');
    Route::post('roles_mass_destroy', ['uses' => 'Admin\RolesController@massDestroy', 'as' => 'roles.mass_destroy']);
    Route::resource('users', 'Admin\UsersController');
    Route::post('users_mass_destroy', ['uses' => 'Admin\UsersController@massDestroy', 'as' => 'users.mass_destroy']);
    Route::resource('categories', 'CategoryController');
    Route::post('category._mass_destroy', ['uses' => 'CategoryController@massDestroy', 'as' => 'categories.mass_destroy']);
    Route::resource('brands', 'BrandController');
    Route::post('brand._mass_destroy', ['uses' => 'BrandController@massDestroy', 'as' => 'brands.mass_destroy']); 
    Route::resource('jobs', 'JobController');
    Route::post('job._mass_destroy', ['uses' => 'JobController@massDestroy', 'as' => 'jobs.mass_destroy']);  
    Route::resource('employees', 'EmployeeController');
    Route::post('employee._mass_destroy', ['uses' => 'EmployeeController@massDestroy', 'as' => 'employees.mass_destroy']);
    Route::resource('products', 'ProductController');
    Route::post('product._mass_destroy', ['uses' => 'ProductController@massDestroy', 'as' => 'products.mass_destroy']);
    Route::resource('takeorders', 'TakeOrderController');
    Route::get('take', ['uses' => 'TakeOrderController@take', 'as' => 'takeorders.take']);
    Route::put('take/{id}', ['uses' => 'TakeOrderController@takeUpdate', 'as' => 'takeorders.takeedit']);

    Route::resource('orders', 'OrderController');
    Route::post('order._mass_destroy', ['uses' => 'OrderController@massDestroy', 'as' => 'orders.mass_destroy']);    
    Route::resource('orderitems', 'OrderItemController');
    Route::post('orderitem._mass_destroy', ['uses' => 'OrderItemController@massDestroy', 'as' => 'orderitems.mass_destroy']);
    Route::resource('tables', 'TableController');
    Route::post('table._mass_destroy', ['uses' => 'TableController@massDestroy', 'as' => 'tables.mass_destroy']);

    Route::get('pdf/{id}', ['uses' => 'PdfController@invoice', 'as' => 'pdf.order']);

    Route::get('report/date', ['uses' => 'OrderController@report', 'as' => 'orders.report']);
    Route::get('report/date/generate', ['uses' => 'OrderController@generate', 'as' => 'orders.generate']);

              

});

app/Order.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Order extends Model
{
        
    protected $table = 'orders';

    protected $fillable =    ['creation_date', 'order_status', 'user_id', 'table_id'];

    public function user()
    {
    	return $this->belongsTo('App\User');
    } 

    public function orderitem()
    {
    	return $this->hasOne('App\OrderItem');
    } 

    public function table()
    {
        return $this->belongsTo('App\Table');
    }     


}

app/Http/Controllers/OrderController.php
<?php

namespace App\Http\Controllers;

use App\Order;
use App\OrderItem;
use Illuminate\Http\Request;
use DB;

class OrderController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $orders = Order::all();
        return view('admin.orders.index', compact('orders'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Order  $order
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $order = Order::where('id', $id)->first();

        $items = OrderItem::where('order_id', $id)->get();
        return view('admin.orders.show', compact('order', 'items'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Order  $order
     * @return \Illuminate\Http\Response
     */
    public function edit(Order $order)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Order  $order
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
          $order = Order::where('id', $id);

          $order->update(['order_status' => 3]);

          return redirect('/admin/orders');        

    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Order  $order
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
          $order = Order::where('id', $id);

          $order->update(['order_status' => 2]);

          return redirect('/admin/orders');
    }

    public function massDestroy(Request $request)
    {

    }  

    public function report()
    {
        $orders = Order::all();
        return view('admin.orders.report', compact('orders'));
    } 

    public function generate(Request $request)
    {
       // $orders = Order::whereBetween('creation_date', $request->toArray())->get();
        $date = $request['min'].' '.$request['max'];

        /*DB::table('orders')
                ->whereBetween('creation_date', $request->toArray())
                ->get();        
*/
        //return view('admin.orders.report', compact('orders'));
       

        $foods = DB::table('order_items')
            ->join('products', 'order_items.product_id', '=', 'products.id')
            ->where('product_type', 2)
            ->whereBetween('order_items.created_at', $request->toArray())
            ->select('order_items.order_id','products.name', 'order_items.price')->get();

        $total_f = DB::table('order_items')
            ->join('products', 'order_items.product_id', '=', 'products.id')
            ->where('product_type', 2)
            ->whereBetween('order_items.created_at', $request->toArray())
            ->sum('order_items.price');            

        $drinks = DB::table('order_items')
            ->join('products', 'order_items.product_id', '=', 'products.id')
            ->where('product_type', 1)
            ->whereBetween('order_items.created_at', $request->toArray())
            ->select('order_items.order_id','products.name', 'order_items.price')->get();

        $total_d = DB::table('order_items')
            ->join('products', 'order_items.product_id', '=', 'products.id')
            ->where('product_type', 1)
            ->whereBetween('order_items.created_at', $request->toArray())
            ->sum('order_items.price');



        $view =  \View::make('admin.invoice.report', compact('foods','drinks', 'total_d', 'total_f', 'date'))->render();

        $pdf = \App::make('dompdf.wrapper');
        $pdf->loadHTML($view);
        return $pdf->stream('report');
    }     


}

resources/views/admin/orders/index.blade.php
@inject('request', 'Illuminate\Http\Request')
@extends('layouts.app')

@section('content')
    <h3 class="page-title">@lang('global.orders.title')</h3>

    <div class="panel panel-default">
        <div class="panel-heading">
            @lang('global.app_list')
        </div>

        <div class="panel-body table-responsive">

<p>
{!! Form::label('table_filter', 'Status', ['class' => 'control-label']) !!}
<select id="table-filter" class="form-control">
<option value="">All</option>
<option value="1">Open</option>
<option value="3">Close</option>
</select>
</p>





<table id="products" class="display" cellspacing="0" width="100%">
                <thead>
                    <tr>
                        <td style="display:none;"></td>
                        <th>#</th>
                        <th>@lang('global.orders.fields.date')</th>
                        <th>@lang('global.orders.fields.status')</th>
                        <th>@lang('global.orders.fields.employee')</th>
                        <th>&nbsp;</th>

                    </tr>
                </thead>
                
                <tbody>
                    @if (count($orders) > 0)
                        @foreach ($orders as $order)
                            <tr data-entry-id="{{ $order->id }}">
                                <td style="display:none;">{{$order->order_status}}</td>
                                <td>{{$order->id}}</td>
                                <td>{{ $order->creation_date }}</td>
                                <td>
                                    @switch($order->order_status)
                                         @case(1)
                                            <span class="label label-primary">Open</span>
                                            @break

                                        @case(2)
                                            <span class="label label-danger">Cancel</span>
                                            @break

                                        @default
                                            <span class="label label-success">Close</span>
                                    @endswitch
                                    
                                </td>
                                <td>{{ \Auth::user()->name }}</td>
                                <td>
                                <a href="{{ route('admin.orders.show', $order->id) }}" class="btn btn-xs btn-primary">@lang('global.app_view')</a>

                                    @if($order->order_status < 2)
                                    <a href="{{ route('admin.orderitems.show',[$order->id]) }}" class="btn btn-xs btn-info">@lang('global.app_edit')</a>                                    
                                        {!! Form::open(array(
                                            'style' => 'display: inline-block;',
                                            'method' => 'PUT',
                                            'onsubmit' => "return confirm('".trans("global.app_are_you_sure")."');",
                                            'route' => ['admin.orders.update', $order->id])) !!}
                                        {!! Form::submit(trans('global.app_close'), array('class' => 'btn btn-xs btn-success')) !!}
                                        {!! Form::close() !!}

                                        {!! Form::open(array(
                                            'style' => 'display: inline-block;',
                                            'method' => 'DELETE',
                                            'onsubmit' => "return confirm('".trans("global.app_are_you_sure")."');",
                                            'route' => ['admin.orders.destroy', $order->id])) !!}
                                        {!! Form::submit(trans('global.app_cancel'), array('class' => 'btn btn-xs btn-danger')) !!}
                                        {!! Form::close() !!}

                                    @endif 
                                <a href="{{ route('admin.pdf.order', $order->id) }}" target="_blank" class="btn btn-xs btn-primary">Print</a>                                                                       
                                </td>

                            </tr>
                        @endforeach
                    @else
                        <tr>
                            <td colspan="9">@lang('global.app_no_entries_in_table')</td>
                        </tr>
                    @endif
                </tbody>
            </table>
        </div>
    </div>
@stop

@section('javascript') 

<script type="text/javascript">
 $(document).ready(function (){
    var table = $('#products').DataTable({
        dom: 'lrtip',
        "bPaginate": false,
        "bLengthChange": false,
    });
    
    $('#table-filter').on('change', function(){
       table.column().search(this.value).draw();   
    });


});
   

</script>

@endsection

resources/views/admin/orders/report.blade.php
@inject('request', 'Illuminate\Http\Request')
@extends('layouts.app')

@section('content')
    <h3 class="page-title">@lang('global.orders.title')</h3>

    <div class="panel panel-default">
        <div class="panel-heading">
            @lang('global.app_list')
        </div>

        <div class="panel-body table-responsive">


    {!! Form::open(['method' => 'GET', 'route' => ['admin.orders.generate']]) !!}

    <div class="panel panel-default">
        
        <div class="panel-body">
            <div class="row">
                <div class="col-xs-12 form-group">
                    {!! Form::label('min', 'Start Date', ['class' => 'control-label']) !!}
                    {!! Form::text('min', old('min'), ['class' => 'form-control', 'id' => 'min']) !!}       
                </div>
            </div>
            <div class="row">
                <div class="col-xs-12 form-group">
                    {!! Form::label('max', 'End Date', ['class' => 'control-label']) !!}
                    {!! Form::text('max', old('max'), ['class' => 'form-control', 'id' => 'max']) !!}
                </div>
            </div>            
        </div>
    </div>

    {!! Form::submit('Generate', ['class' => 'btn btn-danger']) !!}
    {!! Form::close() !!}







        </div>
    </div>
@stop

@section('javascript') 



@endsection

resources/views/admin/orders/reporte.blade.php
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>

    <title>Order #{{$order->id}}</title>
    <link href="{{ url('css/pdf.css') }}" rel="stylesheet">

  </head>
  <body>

    <main>
   @if($drinks)   
      <div id="details" class="clearfix">
        <div id="invoice">
          <h1>ORDER {{ $order->id }}</h1>
          <h3>Drinks</h3>
          <div class="date">Date: {{ $order->creation_date }}</div>
          <div class="date">Table: {{ $table->name }}</div>
        </div>
      </div>
      <table border="0" cellspacing="0" cellpadding="0">
        <thead>
          <tr>
            <th class="desc">DESCRIPTION</th>
            <th class="desc">CATEGORY</th>
            <th class="unit">UNIT PRICE</th>
            <th class="total">OBSERVATION</th>
          </tr>
        </thead>
        <tbody>  
        @foreach($items as $key => $item)  
        @if($products[$key]->product_type == 1)
          <tr>
            <td class="desc">{{ $products[$key]->name }}</td>
            <td class="desc">{{ $categories[$products[$key]->category_id]}}</td>
            <td class="unit">{{ $item->price }}</td>
            <td class="total">{{ $item->observation }} </td>
          </tr>
         @endif
        @endforeach
        </tbody>
        <tfoot>
          <tr>
            <td colspan="2"></td>
            <td >TOTAL</td>
            <td>{{$total_f}}</td>
          </tr>
        </tfoot>
      </table>
      @endif

@if($foods)
      <div id="details" class="clearfix">
        <div id="invoice">
          <h1>ORDER {{ $order->id }}</h1>
          <h3>Foods</h3>
          <div class="date">Date: {{ $order->creation_date }}</div>
          <div class="date">Table: {{ $table->name }}</div>
        </div>
      </div>
      <table border="0" cellspacing="0" cellpadding="0">
        <thead>
          <tr>
            <th class="desc">DESCRIPTION</th>
            <th class="desc">CATEGORY</th>
            <th class="unit">UNIT PRICE</th>
            <th class="total">OBSERVATION</th>
          </tr>
        </thead>
        <tbody>  
        @foreach($items as $key => $item)  
        @if($products[$key]->product_type == 2)
          <tr>
            <td class="desc">{{ $products[$key]->name }}</td>
            <td class="desc">{{ $categories[$products[$key]->category_id]}}</td>
            <td class="unit">{{ $item->price }}</td>
            <td class="total">{{ $item->observation }} </td>
          </tr>
         @endif
        @endforeach
        </tbody>
        <tfoot>
          <tr>
            <td colspan="2"></td>
            <td >TOTAL</td>
            <td>{{$total_d}}</td>
          </tr>
        </tfoot>
      </table>
@endif

      <div id="details" class="clearfix">
        <div id="invoice">
          <h1>ORDER {{ $order->id }}</h1>
          <div class="date">Date: {{ $order->creation_date }}</div>
          <div class="date">Table: {{ $table->name }}</div>
        </div>
      </div>
      <table border="0" cellspacing="0" cellpadding="0">
        <thead>
          <tr>
            <th class="desc">DESCRIPTION</th>
            <th class="desc">CATEGORY</th>
            <th class="unit">UNIT PRICE</th>
            <th class="total">OBSERVATION</th>
          </tr>
        </thead>
        <tbody>  
        @foreach($items as $key => $item)  
          <tr>
            <td class="desc">{{ $products[$key]->name }}</td>
            <td class="desc">{{ $categories[$products[$key]->category_id]}}</td>
            <td class="unit">{{ $item->price }}</td>
            <td class="total">{{ $item->observation }} </td>
          </tr>
        @endforeach
        </tbody>
        <tfoot>
          <tr>
            <td colspan="2"></td>
            <td >TOTAL</td>
            <td>{{$total}}</td>
          </tr>
        </tfoot>
      </table>

  </body>
</html>

resources/views/admin/orders/show.blade.php
@extends('layouts.app')

@section('content')
    <h3 class="page-title">@lang('global.orders.title')</h3>
    <p> 
        <a href="{{ url('admin/orders') }}" class="btn btn-success">@lang('global.app_back')</a>
    </p>    
    <div class="panel panel-default">
        <div class="panel-heading">
            @lang('global.app_edit')
        </div>

        <div class="panel-body">
            <div class="row">
                <div class="col-xs-12 form-group">
                    {!! Form::label('id', 'Order Number', ['class' => 'control-label']) !!}
                    {!! Form::text('id', $order->id, ['class' => 'form-control']) !!}
                </div>
            </div>
          <div class="row">
                <div class="col-xs-12 form-group">
                    {!! Form::label('order_status', 'Order Status', ['class' => 'control-label']) !!}
                    @switch($order->order_status)
                        @case(1)
                            {!! Form::text('order_status', 'Open', ['class' => 'form-control']) !!}
                            @break
                        @case(2)
                            {!! Form::text('order_status', 'Cancel', ['class' => 'form-control']) !!}
                            @break  
                        @default
                            {!! Form::text('order_status', 'Close', ['class' => 'form-control']) !!}
                    @endswitch                                                      

                </div>
            </div>
          <div class="row">
                <div class="col-xs-12 form-group">
                    {!! Form::label('user_id', 'User', ['class' => 'control-label']) !!}
                    {!! Form::text('user_id', $order->user->name, ['class' => 'form-control']) !!}
                </div>
            </div>   
          <div class="row">
                <div class="col-xs-12 form-group">
                    {!! Form::label('table_id', 'Table', ['class' => 'control-label']) !!}
                    {!! Form::text('table_id', $order->table->name, ['class' => 'form-control']) !!}
                </div>
            </div> 
          <div class="row">
                <div class="col-xs-12 form-group">

                    <table class="table">
                      <thead>
                        <tr>
                          <th scope="col">Product</th>
                          <th scope="col">Price</th>
                          <th scope="col">Observation</th>
                        </tr>
                      </thead>
                      <tbody>
                    @if (count($items) > 0)

                        @foreach ($items as $item)

                                <tr>
                                  <td>{{$item->product->name}}</td>
                                  <td>{{$item->price}}</td>
                                  <td>{{$item->observation}}</td>
                                </tr>
                        @endforeach  
                    @endif          
                      </tbody>
                    </table>







                </div>
            </div> 


        </div>
    </div>



@stop